### ISSUE TITLE
I'm new to game development and creating a game with blueprint on UE5.4. Can you guide me on how to solve the jumping down issue. I want my character to start running as soon as he hits the ground

### ISSUE THREAD

**Issue by RoninArts** [MrRobinOfficial/Guide-UnrealEngine#11]
https://github.com/MrRobinOfficial/Guide-UnrealEngine/assets/174161023/4ec3fcb8-e150-41d4-bb67-d7dd164f1e6b

Here is the issue: When my character lands on the ground after jumping, it slides then start running.

**Comment by MrRobinOfficial** [comment]
Hi there! A couple of points. If you have issues unrelated to this repository, **please reach out to me privately via email or another platform instead of using this issue tracker**. Since this issue tracker is only related to spelling mistakes or incorrect statements made in this repo.

Additionally, when recording, **please consider using software like OBS, Nvidia Game Capture, or a similar tool for clearer footage**.

Regarding your specific issue, unfortunately, I can't provide a concrete solution since I would need to require the complete project files. If you're following a tutorial, I recommend reviewing it thoroughly to identify any potential mistakes, especially in the Animation Blueprint.

**From the footage you've shared, it appears the character isn't animating properly after the jump sequence, suggesting an issue with interrupting the current animation when transitioning to a run or walk animation.**

I would suggest those videos if you are stuck with the animation blueprint:

[How to Animate Your Character in Unreal Engine 5 - Animation Blueprints and Blendspaces](https://www.youtube.com/watch?v=WUXvq6At6pE)
[Unreal Engine 5 Tutorial - Animation Blueprint Part 1: State Machines](https://www.youtube.com/watch?v=etRZu5UG_S0)
[How To Make An Animation Blueprint In Unreal Engine 5.1 | How To Animate A Character - UE5 Tutorial](https://www.youtube.com/watch?v=qbgDaRo312k)

I hope these tutorials will provide a solution to your issue.
Happy learning!

Cheers,
Robin.
